[project]
name = "radps"
version = "0.0.1"
description = "RADPS"
authors = [
    {name = "RADPS Scrum Team"},
]
license = {file = "LICENSE.txt"}
readme = "README.md"
requires-python = "==3.13.2"

dependencies = [
'dask==2025.4.1',
'distributed==2025.4.1',
'prefect==3.4.0',
'prefect_dask==0.3.4',
'pandas==2.2.3',
'prefect_sqlalchemy==0.5.2'
]


