apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect-ingress
spec:
  rules:
    - host: prefect.noop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prefect-server
                port:
                  number: 4200
