apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radps-hub

resources:
  - ../../base

patches:
  - path: pvc-patch.yaml

helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    releaseName: jupyterhub
    namespace: radps-hub
    valuesFile: jupyterhub-values.yaml
