worker:
  config:
    workPool: Test

  apiConfig: "server"

  serverApiConfig:
    # If the prefect server is located external to this cluster, set a fully qualified domain name as the apiUrl
    # If the prefect server pod is deployed to this cluster, use the cluster DNS endpoint: http://<prefect-server-service-name>.<namespace>.svc.cluster.local:<prefect-server-port>/api
    # -- prefect API url (PREFECT_API_URL)
    apiUrl: "http://prefect-server.default.svc.cluster.local:4200/api"
    # -- prefect UI url
    uiUrl: http://localhost:4200
