# common-storage-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radps-hub-pvc
  namespace: radps-hub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn          
  resources:
    requests:
      storage: 1Ti