import time
import requests
import dask.array as da
import scipy
from matplotlib.image import imsave
import pathlib
from prefect import flow, task
from prefect.cache_policies import TASK_SOURCE

from example_calibration_pipeline import create_qa_artifact

# Implemetation of the example pipeline from Figure 1
# of "An Example RADPS Workflow Decomposition"

# Calibrator Data Import and Prep

# Bandpass Solve

# Time Gain Solve

# Image Calibrators


# Target Data Import and Prep
@task
def fake_archive_query() -> dict:
    print("Pretending to fetch some data from an archive")
    time.sleep(da.random.randint(low=1, high=10, size=1))
    print(
        "Now that that latency simulation is complete, generating some mock data to return"
    )
    rng = da.random.default_rng()
    target_vals = rng.standard_normal(size=(1200, 1200, 30, 4))
    calibrator_vals = rng.standard_normal(size=(100, 100, 10, 4))

    fake_result = {
        "data": {
            "source_0": calibrator_vals,
            "source_1": target_vals,
        },
        "data_source": "archive",
        "url": "https://almascience.nrao.edu/aq/",
    }

    return fake_result


@task(refresh_cache=True)
def fake_flagging(fake_result, target) -> dict:
    print("Performing a dummy sub-selection step")
    time.sleep(2)
    transformed_data = fake_result

    # some "heuristic" to remove the "other" source from the fake_result generated by fake_archive_query
    if target.endswith("0"):
        key_to_drop = target[:-1] + "1"
    elif target.endswith("1"):
        key_to_drop = target[:-1] + "0"

    transformed_data["data"].pop(f"{key_to_drop}")

    return transformed_data


@task(cache_policy=TASK_SOURCE)
def alma_antpos_query() -> dict:
    print("Requesting some data from an external antenna position service")
    response = requests.get(
        "http://asa.alma.cl/axis2/services/TMCDBAntennaPadService?wsdl"
    )
    try:
        antpos_result_json = response.json()["data"]
    except requests.exceptions.JSONDecodeError:
        print(
            "Oh no, there was an issue with the query! Proceeding with empty result object."
        )
        antpos_result_json = {}

    return antpos_result_json


@task
def generate_caltable(antpos_result_json):
    print(
        "Pretending to generate a caltable using the results of an antenna position service query"
    )
    time.sleep(4)
    caltable = {"gains": da.random.random_sample(size=(4))}

    return caltable


@task
def apply_caltable(uncalibrated_data, caltable, target):
    print("Pretending to apply a transformation on some data using a calibration table")
    calibrated_data = uncalibrated_data
    calibrated_data["data"][target] = (
        caltable["gains"] * uncalibrated_data["data"][target]
    )

    return calibrated_data


@flow
def generate_and_apply_gain_table(
    uncalibrated_data, antpos_result_json, target
) -> dict:
    print(
        "Calling tasks that generate some data and use it to transform some other data"
    )
    caltable = generate_caltable(antpos_result_json)
    calibrated_data = apply_caltable(uncalibrated_data, caltable, target)

    return calibrated_data


@flow
def extract_transform_load(source_name) -> dict:
    print("Calling archive query task")
    fake_data = fake_archive_query()

    print("Calling flagging task")
    transformed_data = fake_flagging(fake_data, source_name)

    print("Calling antpos query task")
    antpos_query_result = alma_antpos_query()

    print(
        "Checking to see if we can/should try to perform antenna position corrections"
    )
    if antpos_query_result == {}:
        # treat an empty dictionary as expected input, just so we can see the conditional flow
        print("Seems like we have a result. Running conditional flow")
        calibrated_data = generate_and_apply_gain_table(
            transformed_data, antpos_query_result, source_name
        )
    else:
        print("Looks like we don't have a result. Skipping conditional flow")

    print("Returning results of the target data import and prep stage")
    try:
        return calibrated_data
    except NameError:
        return transformed_data


# Calibrate Target and Find Continuum
@task
def make_qa_score() -> dict:
    print(
        "Pretending to perform computation that determines a QA score to return to some pipeline context"
    )

    # contains an iterative solver (sometimes)
    # for now, just calculate some moments on an array of random data
    rng = da.random.default_rng()
    random_array = rng.standard_normal(size=(1000, 1000, 10, 4))

    qa_result = {
        "stage": da.random.randint(low=1, high=42).compute().item(),
    }

    # calculate a few statistical moments
    for order in range(2, 9):
        metric = da.moment(random_array, order=order).compute().item()
        qa_result[f"order{order}"] = metric

    # arbitrarily check the value of the last moment to determine Pass/Fail
    if qa_result[f"order{order}"] > 105:
        result = True
    else:
        result = False

    qa_result["pass"] = result

    print("Calculated a fake QA score. Result:")
    print(qa_result)

    return qa_result


@flow
def make_dirty_cube(fake_visibilities) -> dict:
    print("Pretending to construct a dirty image cube from some target data")
    fake_image = fake_visibilities

    print("Simulating an 'iterative solver' by looping on some axis ")
    for nn in range(0, fake_visibilities["data"]["source_1"].shape[3]):
        fake_image["data"]["source_1"] = da.fft.fft2(
            da.rechunk(fake_visibilities["data"]["source_1"], chunks=-1)
        )
        fake_image["data"]["source_1"].compute()

    dirty_cube = fake_image

    return dirty_cube


@task
def calculate_mean_spectrum(dirty_cube) -> dict:
    print(
        "Pretending to calculate a mean spectrum for determining line-free channels in a dirty image cube"
    )
    time.sleep(2)
    mean_spectrum = dirty_cube["data"]["source_1"].mean(axis=2).compute()

    return mean_spectrum


@task
def peak_over_MAD(mean_spectrum) -> dict:
    print(
        "Pretending to use median absolute deviation method to find line-free channels"
    )
    time.sleep(6)
    continuum_data = {"result": scipy.stats.median_abs_deviation(mean_spectrum)}

    return {}


@flow
def find_continuum(dirty_cube) -> dict:
    print(
        "Pretending to perform some heuristics to identify line-free channels in a dirty cube image"
    )
    spectrum_from_image = calculate_mean_spectrum(dirty_cube)
    continuum_data = peak_over_MAD(spectrum_from_image)

    return continuum_data


@flow
def calibrate_target_and_find_continuum(input_data) -> dict:
    print(
        "Starting a pipeline stage that applies calibration to target and finds line-free continuum"
    )
    dummy_caltable = {"gains": da.random.random_sample(size=(4))}
    calibrated_data = apply_caltable(input_data, dummy_caltable, "source_1")

    stage_result = make_qa_score()
    create_qa_artifact(stage_result, artifact_type="table")

    dirty_cube = make_dirty_cube(calibrated_data)

    # just write a slice of our fake image to disk
    imsave("image.png", calibrated_data["data"]["source_1"][:,:,0,0].compute())
    stage_result["url"] = pathlib.Path("image.png").resolve().as_uri()
    create_qa_artifact(stage_result, artifact_type="image")

    continuum_data = find_continuum(dirty_cube)

    return dirty_cube, continuum_data


# Cube Imaging

# Continuum Imaging with Self-Calibration

# Per-SPW Continuum Imaging

if __name__ == "__main__":

    # Calibrator Data Import and Prep
    calibrator_data = extract_transform_load("source_0")

    # TODO:
    # Bandpass Solve
    # Time Gain Solve
    # Image Calibrators
    # TODO ^^^

    # Target Data Import and Prep
    target_data = extract_transform_load("source_1")

    # Calibrate Target and Find Continuum
    dirty_image, findcont = calibrate_target_and_find_continuum(target_data)

    # TODO:
    # Cube Imaging
    # Continuum Imaging with Self-Calibration
    # Per-SPW Continuum Imaging
