import requests
import dask.array as da
from matplotlib.image import imsave
import pathlib

from prefect import flow, task
from prefect.cache_policies import TASK_SOURCE
from prefect.logging import get_run_logger
from prefect_dask import DaskTaskRunner
import dask.distributed

from core import (
    sleep_placeholder,
    create_qa_artifact,
    fake_qa_score,
    add_to_context,
    load_context,
    randomly_fail,
    fake_data_generator,
)
from resource_management import connect_to_scheduler

tr = connect_to_scheduler()


# Target Data Import and Prep
@task(log_prints=True, retries=4, tags=["io"])
def fake_archive_query(dataset_name: str = "", failures: bool = False) -> dict:
    """
    Simulate importing data from the archive.
    """
    if randomly_fail(on=failures):
        raise Exception(f"Import data: {dataset_name} from archive failed")

    print(f"Pretending to fetch data for {dataset_name} from an archive")
    sleep_placeholder(3)
    print(
        "Now that that latency simulation is complete, generating some mock data to return"
    )
    datashape = {
        "target": {"n_field": 1, "n_spw": 3, "n_scan": 27},
        "calibrator": {"n_field": 1, "n_spw": 3, "n_scan": 5},
    }
    context = add_to_context(datashape, key="datashape", stage="data_import_and_prep")

    target_vals = fake_data_generator(datashape["target"], "vis")
    calibrator_vals = fake_data_generator(datashape["calibrator"], "vis")

    if dataset_name == "":
        dataset_name = "source_0"

    fake_result = {
        "data": {
            dataset_name: calibrator_vals,
            "source_1": target_vals,
        },
        "data_source": "core",
        "url": "https://almascience.nrao.edu/aq/",
    }

    context = add_to_context(
        fake_result["data"], key="data", stage="data_import_and_prep"
    )

    return fake_result


@task(log_prints=True, refresh_cache=True, tags=["flagging"])
def fake_flagging(fake_result, source_name: str) -> dict:
    """
    Simulate flagging.
    """
    print("Performing a dummy sub-selection step")
    sleep_placeholder(2)
    transformed_data = fake_result

    # Some "heuristic" to remove the "other" source from the fake_result generated by fake_archive_query if present
    key_to_drop = None

    if source_name.endswith("0"):
        key_to_drop = source_name[:-1] + "1"
    elif source_name.endswith("1"):
        key_to_drop = source_name[:-1] + "0"

    if key_to_drop:
        transformed_data["data"].pop(f"{key_to_drop}")

    context = add_to_context(transformed_data, "data", "data_import_and_prep")

    return transformed_data


@task(cache_policy=TASK_SOURCE)
def alma_antpos_query(tags=["io"]) -> dict:
    """
    Simulate querying the alma archive.
    """
    logger = get_run_logger()
    logger.info("Requesting some data from an external antenna position service")

    response = requests.get(
        "http://asa.alma.cl/axis2/services/TMCDBAntennaPadService?wsdl"
    )
    try:
        antpos_result_json = response.json()["data"]
    except requests.exceptions.JSONDecodeError:
        logger.error(
            "Oh no, there was an issue with the query! Proceeding with empty result object."
        )
        antpos_result_json = {}

    context = add_to_context(
        {"response": antpos_result_json}, "data", "data_import_and_prep"
    )

    print("Creating a synthentic gcal result to add to the context")
    datashape = {
        "calibrator": {"n_field": 1, "n_spw": 3, "n_scan": 5},
    }
    context = add_to_context(datashape, "datashape", "data_import_and_prep")
    gcal_data = fake_data_generator(datashape["calibrator"], "gcal")
    context = add_to_context({"gcal": gcal_data}, "data", "data_import_and_prep")

    return antpos_result_json


@task
def generate_caltable(antpos_result_json):
    print(
        "Pretending to generate a caltable using the results of an antenna position service query"
    )
    sleep_placeholder(4)

    datashape = {
        "calibrator": {"n_field": 1, "n_spw": 3, "n_scan": 5},
    }
    gcal_data = fake_data_generator(datashape["calibrator"], "gcal")
    context = add_to_context({"gcal": gcal_data}, "data", "data_import_and_prep")

    return gcal_data


@task
def apply_caltable(uncalibrated_data, caltable, target):
    print("Pretending to apply a transformation on some data using a calibration table")
    calibrated_data = uncalibrated_data
    calibrated_data["data"][target] = (
        da.take(caltable, indices=-1, axis=1) * uncalibrated_data["data"][target]
    )

    context = add_to_context(calibrated_data, "data", "data_import_and_prep")

    return calibrated_data


@flow
def generate_and_apply_gain_table(
    uncalibrated_data, antpos_result_json, target
) -> dict:
    print(
        "Calling tasks that generate some data and use it to transform some other data"
    )
    caltable = generate_caltable(antpos_result_json)
    calibrated_data = apply_caltable(uncalibrated_data, caltable, target)

    return calibrated_data


@flow(log_prints=True, task_runner=tr)
def extract_transform_load(source_name) -> dict:
    logger = get_run_logger()

    etl_context = load_context()
    print(f"Initial context: {etl_context}")

    logger.info("Calling archive query task")
    fake_data = fake_archive_query()

    logger.info("Calling flagging task")
    transformed_data = fake_flagging(fake_data, source_name)

    logger.info("Calling antpos query task")
    antpos_query_result = alma_antpos_query()

    logger.info(
        "Checking to see if we can/should try to perform antenna position corrections"
    )
    if antpos_query_result == {}:
        # treat an empty dictionary as expected input, just so we can see the conditional flow
        logger.debug("Seems like we have a result. Running conditional flow")
        calibrated_data = generate_and_apply_gain_table(
            transformed_data, antpos_query_result, source_name
        )
    else:
        logger.debug("Looks like we don't have a result. Skipping conditional flow")

    logger.info("Returning results of the target data import and prep stage")
    try:
        qa_score = fake_qa_score("data_import_and_prep", result=calibrated_data)
        create_qa_artifact(qa_score)
        etl_context = add_to_context(qa_score, "qa", "data_import_and_prep")
        print(f"Final context: {etl_context}")
        return calibrated_data
    except NameError:
        logger.debug(
            f"Caught NameError attempting return of generate_and_apply_gain_table output"
        )
        qa_score = fake_qa_score("data_import_and_prep", result=transformed_data)
        create_qa_artifact(qa_score)
        etl_context = add_to_context(qa_score, "qa", "data_import_and_prep")
        print(f"Final context: {etl_context}")
        return transformed_data


if __name__ == "__main__":

    # Target Data Import and Prep
    target_data = extract_transform_load("source_1")
