scheduler:
  name: scheduler # Dask scheduler name.
  enabled: true # Enable/disable scheduler.
  image:
    repository: "ghcr.io/dask/dask" # Container image repository.
    tag: "2025.1.0" # Container image tag.
    pullPolicy: IfNotPresent # Container image pull policy.
    pullSecrets: # Container image [pull secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).
  replicas: 1 # Number of schedulers (should always be 1).
  serviceType: "ClusterIP" # Scheduler service type. Set to `LoadBalancer` to expose outside of your cluster.
  #serviceType: "LoadBalancer"
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 2G
  env:
    - name: EXTRA_PIP_PACKAGES
      value: prefect
  
jupyter:
  name: jupyter # Jupyter name.
  enabled: false # Enable/disable the bundled Jupyter notebook.

worker:
  name: worker # Dask worker name.
  image:
    repository: "ghcr.io/dask/dask" # Container image repository.
    tag: "2025.1.0" # Container image tag.
    pullPolicy: IfNotPresent # Container image pull policy.
    dask_worker: "dask-worker" # Dask worker command. E.g `dask-cuda-worker` for GPU worker.
    pullSecrets: # Container image [pull secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).
    #  - name: regcred
  metrics:
    enabled: false # Enable workers metrics. Pip package [prometheus-client](https://pypi.org/project/prometheus-client/) should be present on workers.
  replicas: 3 # Number of workers.
  strategy:
    type: RollingUpdate # Strategy used to replace old Pods with new ones.
  resources:  # Worker pod resources. See `values.yaml` for example values.
    limits:
      cpu: 1
      memory: 3G
    requests:
      cpu: 0.5
      memory: 2G
  env:
    - name: EXTRA_PIP_PACKAGES
      value: prefect
